apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flask-app
type: Opaque  # Tipo genérico para datos arbitrarios (texto, JSON, binario)
stringData:  # Los valores se codifican automáticamente a base64
  POSTGRES_USER: flaskuser
  POSTGRES_PASSWORD: flaskpass123
  POSTGRES_DB: flaskdb