apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: flask-app
spec:
  accessModes:
    - ReadWriteOnce  # Solo un nodo puede montar este volumen en modo lectura-escritura
  resources:
    requests:
      storage: 1Gi  # Solicita 1 GB de almacenamiento
  storageClassName: hostpath  # Tipo de almacenamiento (ajustar según tu clúster: standard, hostpath, etc.)