apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: flask-app
  labels:
    app: nginx
spec:
  type: NodePort  # Cambiar a LoadBalancer si estás en cloud provider
  selector:
    app: nginx
    tier: frontend  # Selecciona los Pods de Nginx
  ports:
    - name: http
      port: 80  # Puerto del Service (interno al cluster)
      targetPort: 80  # Puerto del contenedor Nginx
      nodePort: 30080  # Puerto expuesto en el nodo (solo para NodePort)
      protocol: TCP